/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'userName' : IDL.Text,
  'text' : IDL.Text,
  'userPhoto' : IDL.Text,
  'timestamp' : Time,
  'postId' : IDL.Text,
});
export const NotificationType = IDL.Variant({
  'likePost' : IDL.Null,
  'likePhoto' : IDL.Null,
  'commentPost' : IDL.Null,
  'likePrompt' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'notificationType' : NotificationType,
  'read' : IDL.Bool,
  'text' : IDL.Text,
  'toUserId' : IDL.Principal,
  'fromPhoto' : IDL.Text,
  'timestamp' : Time,
  'fromName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Match = IDL.Record({
  'screenshotAttemptFlag' : IDL.Bool,
  'matchCreatedTime' : Time,
  'matchId' : IDL.Text,
  'isMatched' : IDL.Bool,
  'user1' : IDL.Principal,
  'user2' : IDL.Principal,
  'chatDeleted' : IDL.Bool,
  'firstMessageSent' : IDL.Bool,
});
export const ChatMessage = IDL.Record({
  'msgId' : IDL.Text,
  'text' : IDL.Text,
  'sentAt' : Time,
  'matchId' : IDL.Text,
  'senderUserId' : IDL.Principal,
});
export const FeedPost = IDL.Record({
  'id' : IDL.Text,
  'userName' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'userPhoto' : IDL.Text,
  'userAge' : IDL.Nat,
  'postImage' : IDL.Opt(IDL.Text),
  'isVerified' : IDL.Bool,
  'caption' : IDL.Opt(IDL.Text),
  'prompt' : IDL.Opt(IDL.Text),
  'likesCount' : IDL.Nat,
  'promptAnswer' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'isVerified' : IDL.Bool,
  'gender' : IDL.Text,
  'photo' : IDL.Text,
  'planType' : IDL.Text,
});
export const PostData = IDL.Record({
  'key' : IDL.Text,
  'didLike' : IDL.Bool,
  'post' : FeedPost,
  'likesCount' : IDL.Nat,
});
export const Report = IDL.Record({
  'isReviewed' : IDL.Bool,
  'reportedUserId' : IDL.Principal,
  'reportedAt' : Time,
  'reporterUserId' : IDL.Principal,
  'details' : IDL.Text,
  'reportId' : IDL.Text,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, Comment, IDL.Text], [], []),
  'addNotification' : IDL.Func([Notification, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMatch' : IDL.Func(
      [IDL.Principal, IDL.Principal, IDL.Text],
      [Match],
      [],
    ),
  'createMessage' : IDL.Func(
      [ChatMessage, IDL.Text],
      [
        IDL.Variant({
          'message' : IDL.Opt(
            IDL.Record({
              'msgId' : IDL.Text,
              'text' : IDL.Text,
              'sentAt' : Time,
              'matchId' : IDL.Text,
              'senderUserId' : IDL.Principal,
            })
          ),
        }),
      ],
      [],
    ),
  'createNotifications' : IDL.Func(
      [IDL.Principal, NotificationType],
      [IDL.Text],
      [],
    ),
  'createPost' : IDL.Func([FeedPost, IDL.Text], [FeedPost], []),
  'deleteChat' : IDL.Func([IDL.Text], [], []),
  'deleteMatch' : IDL.Func([IDL.Text], [], []),
  'flagScreenshotAttempt' : IDL.Func([IDL.Text], [], []),
  'getBlockedUsers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getBlockingUsers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getLikes' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Principal)], ['query']),
  'getMatch' : IDL.Func([IDL.Text], [IDL.Opt(Match)], ['query']),
  'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
  'getNotifications' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getPosts' : IDL.Func([], [IDL.Vec(PostData)], ['query']),
  'getPostsCreatedToday' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isBlocked' : IDL.Func([IDL.Principal, IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], []),
  'markNotificationsRead' : IDL.Func([IDL.Principal], [], []),
  'markReportReviewed' : IDL.Func([IDL.Text], [], []),
  'reportUser' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'resetDailyLimits' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleBlock' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Variant({
          'blockedSuccessfully' : IDL.Bool,
          'unblockedSuccessfully' : IDL.Bool,
        }),
      ],
      [],
    ),
  'unlikePost' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], []),
  'updatePostsCreatedToday' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'userName' : IDL.Text,
    'text' : IDL.Text,
    'userPhoto' : IDL.Text,
    'timestamp' : Time,
    'postId' : IDL.Text,
  });
  const NotificationType = IDL.Variant({
    'likePost' : IDL.Null,
    'likePhoto' : IDL.Null,
    'commentPost' : IDL.Null,
    'likePrompt' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'notificationType' : NotificationType,
    'read' : IDL.Bool,
    'text' : IDL.Text,
    'toUserId' : IDL.Principal,
    'fromPhoto' : IDL.Text,
    'timestamp' : Time,
    'fromName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Match = IDL.Record({
    'screenshotAttemptFlag' : IDL.Bool,
    'matchCreatedTime' : Time,
    'matchId' : IDL.Text,
    'isMatched' : IDL.Bool,
    'user1' : IDL.Principal,
    'user2' : IDL.Principal,
    'chatDeleted' : IDL.Bool,
    'firstMessageSent' : IDL.Bool,
  });
  const ChatMessage = IDL.Record({
    'msgId' : IDL.Text,
    'text' : IDL.Text,
    'sentAt' : Time,
    'matchId' : IDL.Text,
    'senderUserId' : IDL.Principal,
  });
  const FeedPost = IDL.Record({
    'id' : IDL.Text,
    'userName' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'userPhoto' : IDL.Text,
    'userAge' : IDL.Nat,
    'postImage' : IDL.Opt(IDL.Text),
    'isVerified' : IDL.Bool,
    'caption' : IDL.Opt(IDL.Text),
    'prompt' : IDL.Opt(IDL.Text),
    'likesCount' : IDL.Nat,
    'promptAnswer' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'isVerified' : IDL.Bool,
    'gender' : IDL.Text,
    'photo' : IDL.Text,
    'planType' : IDL.Text,
  });
  const PostData = IDL.Record({
    'key' : IDL.Text,
    'didLike' : IDL.Bool,
    'post' : FeedPost,
    'likesCount' : IDL.Nat,
  });
  const Report = IDL.Record({
    'isReviewed' : IDL.Bool,
    'reportedUserId' : IDL.Principal,
    'reportedAt' : Time,
    'reporterUserId' : IDL.Principal,
    'details' : IDL.Text,
    'reportId' : IDL.Text,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, Comment, IDL.Text], [], []),
    'addNotification' : IDL.Func([Notification, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMatch' : IDL.Func(
        [IDL.Principal, IDL.Principal, IDL.Text],
        [Match],
        [],
      ),
    'createMessage' : IDL.Func(
        [ChatMessage, IDL.Text],
        [
          IDL.Variant({
            'message' : IDL.Opt(
              IDL.Record({
                'msgId' : IDL.Text,
                'text' : IDL.Text,
                'sentAt' : Time,
                'matchId' : IDL.Text,
                'senderUserId' : IDL.Principal,
              })
            ),
          }),
        ],
        [],
      ),
    'createNotifications' : IDL.Func(
        [IDL.Principal, NotificationType],
        [IDL.Text],
        [],
      ),
    'createPost' : IDL.Func([FeedPost, IDL.Text], [FeedPost], []),
    'deleteChat' : IDL.Func([IDL.Text], [], []),
    'deleteMatch' : IDL.Func([IDL.Text], [], []),
    'flagScreenshotAttempt' : IDL.Func([IDL.Text], [], []),
    'getBlockedUsers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getBlockingUsers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getLikes' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Principal)], ['query']),
    'getMatch' : IDL.Func([IDL.Text], [IDL.Opt(Match)], ['query']),
    'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
    'getNotifications' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getPosts' : IDL.Func([], [IDL.Vec(PostData)], ['query']),
    'getPostsCreatedToday' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isBlocked' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], []),
    'markNotificationsRead' : IDL.Func([IDL.Principal], [], []),
    'markReportReviewed' : IDL.Func([IDL.Text], [], []),
    'reportUser' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'resetDailyLimits' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleBlock' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Variant({
            'blockedSuccessfully' : IDL.Bool,
            'unblockedSuccessfully' : IDL.Bool,
          }),
        ],
        [],
      ),
    'unlikePost' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], []),
    'updatePostsCreatedToday' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };