/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'msgId' : string,
  'text' : string,
  'sentAt' : Time,
  'matchId' : string,
  'senderUserId' : Principal,
}
export interface Comment {
  'id' : string,
  'userName' : string,
  'text' : string,
  'userPhoto' : string,
  'timestamp' : Time,
  'postId' : string,
}
export interface FeedPost {
  'id' : string,
  'userName' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'userPhoto' : string,
  'userAge' : bigint,
  'postImage' : [] | [string],
  'isVerified' : boolean,
  'caption' : [] | [string],
  'prompt' : [] | [string],
  'likesCount' : bigint,
  'promptAnswer' : [] | [string],
}
export interface Match {
  'screenshotAttemptFlag' : boolean,
  'matchCreatedTime' : Time,
  'matchId' : string,
  'isMatched' : boolean,
  'user1' : Principal,
  'user2' : Principal,
  'chatDeleted' : boolean,
  'firstMessageSent' : boolean,
}
export interface Notification {
  'id' : string,
  'notificationType' : NotificationType,
  'read' : boolean,
  'text' : string,
  'toUserId' : Principal,
  'fromPhoto' : string,
  'timestamp' : Time,
  'fromName' : string,
}
export type NotificationType = { 'likePost' : null } |
  { 'likePhoto' : null } |
  { 'commentPost' : null } |
  { 'likePrompt' : null };
export interface PostData {
  'key' : string,
  'didLike' : boolean,
  'post' : FeedPost,
  'likesCount' : bigint,
}
export interface Report {
  'isReviewed' : boolean,
  'reportedUserId' : Principal,
  'reportedAt' : Time,
  'reporterUserId' : Principal,
  'details' : string,
  'reportId' : string,
  'reason' : string,
}
export interface Story {
  'id' : string,
  'storyType' : StoryType,
  'userId' : Principal,
  'createdAt' : Time,
  'overlayText' : [] | [string],
  'mediaUrl' : string,
  'viewers' : Array<Principal>,
  'youtubeVidId' : [] | [string],
  'youtubeTtitle' : [] | [string],
  'location' : [] | [string],
}
export type StoryType = { 'video' : null } |
  { 'image' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserPhoto { 'url' : string, 'caption' : string }
export interface UserProfile {
  'age' : bigint,
  'avatarData' : [] | [string],
  'name' : string,
  'isDemo' : boolean,
  'isVerified' : boolean,
  'gender' : string,
  'coverPhotoIndex' : bigint,
  'photo' : string,
  'planType' : string,
  'photos' : Array<UserPhoto>,
  'verificationImage' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, Comment, string], undefined>,
  'addNotification' : ActorMethod<[Notification, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMatch' : ActorMethod<[Principal, Principal, string], Match>,
  'createMessage' : ActorMethod<
    [ChatMessage, string],
    {
        'message' : [] | [
          {
            'msgId' : string,
            'text' : string,
            'sentAt' : Time,
            'matchId' : string,
            'senderUserId' : Principal,
          }
        ]
      }
  >,
  'createNotifications' : ActorMethod<[Principal, NotificationType], string>,
  'createPost' : ActorMethod<[FeedPost, string], FeedPost>,
  'createStory' : ActorMethod<[Story], undefined>,
  'deleteChat' : ActorMethod<[string], undefined>,
  'deleteMatch' : ActorMethod<[string], undefined>,
  'deleteStory' : ActorMethod<[string], undefined>,
  'flagScreenshotAttempt' : ActorMethod<[string], undefined>,
  'getActiveStories' : ActorMethod<[], Array<[Story, bigint]>>,
  'getBlockedUsers' : ActorMethod<[Principal], Array<Principal>>,
  'getBlockingUsers' : ActorMethod<[Principal], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatThemes' : ActorMethod<[], Array<[string, string]>>,
  'getComments' : ActorMethod<[string], Array<Comment>>,
  'getLikes' : ActorMethod<[string], Array<Principal>>,
  'getMatch' : ActorMethod<[string], [] | [Match]>,
  'getMatches' : ActorMethod<[], Array<Match>>,
  'getMessages' : ActorMethod<[string], Array<ChatMessage>>,
  'getMessagesAfter' : ActorMethod<[string, Time], Array<ChatMessage>>,
  'getNotifications' : ActorMethod<[Principal], Array<Notification>>,
  'getPosts' : ActorMethod<[], Array<PostData>>,
  'getPostsCreatedToday' : ActorMethod<[Principal], bigint>,
  'getReports' : ActorMethod<[], Array<Report>>,
  'getStoryViewers' : ActorMethod<[string], [bigint, Array<Principal>]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isBlocked' : ActorMethod<[Principal, Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[string], [] | [bigint]>,
  'markNotificationsRead' : ActorMethod<[Principal], undefined>,
  'markReportReviewed' : ActorMethod<[string], undefined>,
  'markStoryViewed' : ActorMethod<[string], undefined>,
  'reportUser' : ActorMethod<[string, Principal, string, string], undefined>,
  'requestEmailOTP' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'error' : string }
  >,
  'resetDailyLimits' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveChatTheme' : ActorMethod<[string, string], undefined>,
  'setCoverPhoto' : ActorMethod<[bigint], undefined>,
  'setVerificationImage' : ActorMethod<[string], undefined>,
  'toggleBlock' : ActorMethod<
    [Principal],
    { 'blockedSuccessfully' : boolean } |
      { 'unblockedSuccessfully' : boolean }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unlikePost' : ActorMethod<[string], [] | [bigint]>,
  'updatePostsCreatedToday' : ActorMethod<[Principal], undefined>,
  'updateUserPhotos' : ActorMethod<[Array<UserPhoto>, bigint], undefined>,
  'verifyEmailOTP' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'expired' : null } |
      { 'invalid' : null } |
      { 'tooManyAttempts' : null }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];