/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface Comment {
    id: string;
    userName: string;
    text: string;
    userPhoto: string;
    timestamp: Time;
    postId: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Story {
    id: string;
    storyType: StoryType;
    userId: Principal;
    createdAt: Time;
    overlayText?: string;
    mediaUrl: string;
    viewers: Array<Principal>;
    youtubeVidId?: string;
    youtubeTtitle?: string;
    location?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserPhoto {
    url: string;
    caption: string;
}
export interface Report {
    isReviewed: boolean;
    reportedUserId: Principal;
    reportedAt: Time;
    reporterUserId: Principal;
    details: string;
    reportId: string;
    reason: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface PostData {
    key: string;
    didLike: boolean;
    post: FeedPost;
    likesCount: bigint;
}
export interface Match {
    screenshotAttemptFlag: boolean;
    matchCreatedTime: Time;
    matchId: string;
    isMatched: boolean;
    user1: Principal;
    user2: Principal;
    chatDeleted: boolean;
    firstMessageSent: boolean;
}
export interface FeedPost {
    id: string;
    userName: string;
    userId: Principal;
    createdAt: Time;
    userPhoto: string;
    userAge: bigint;
    postImage?: string;
    isVerified: boolean;
    caption?: string;
    prompt?: string;
    likesCount: bigint;
    promptAnswer?: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Notification {
    id: string;
    notificationType: NotificationType;
    read: boolean;
    text: string;
    toUserId: Principal;
    fromPhoto: string;
    timestamp: Time;
    fromName: string;
}
export interface ChatMessage {
    msgId: string;
    text: string;
    sentAt: Time;
    matchId: string;
    senderUserId: Principal;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    age: bigint;
    avatarData?: string;
    name: string;
    isDemo: boolean;
    isVerified: boolean;
    gender: string;
    coverPhotoIndex: bigint;
    photo: string;
    planType: string;
    photos: Array<UserPhoto>;
    verificationImage?: string;
}
export enum NotificationType {
    likePost = "likePost",
    likePhoto = "likePhoto",
    commentPost = "commentPost",
    likePrompt = "likePrompt"
}
export enum StoryType {
    video = "video",
    image = "image"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_ok_expired_invalid_tooManyAttempts {
    ok = "ok",
    expired = "expired",
    invalid = "invalid",
    tooManyAttempts = "tooManyAttempts"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComment(postId: string, comment: Comment, key: string): Promise<void>;
    addNotification(notification: Notification, key: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createMatch(user1: Principal, user2: Principal, matchId: string): Promise<Match>;
    createMessage(incomingMsg: ChatMessage, key: string): Promise<{
        __kind__: "message";
        message: {
            msgId: string;
            text: string;
            sentAt: Time;
            matchId: string;
            senderUserId: Principal;
        } | null;
    }>;
    createNotifications(user: Principal, notifType: NotificationType): Promise<string>;
    createPost(post: FeedPost, key: string): Promise<FeedPost>;
    createStory(story: Story): Promise<void>;
    deleteChat(matchId: string): Promise<void>;
    deleteMatch(matchId: string): Promise<void>;
    deleteStory(storyId: string): Promise<void>;
    flagScreenshotAttempt(matchId: string): Promise<void>;
    getActiveStories(): Promise<Array<[Story, bigint]>>;
    getBlockedUsers(userId: Principal): Promise<Array<Principal>>;
    getBlockingUsers(userId: Principal): Promise<Array<Principal>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatThemes(): Promise<Array<[string, string]>>;
    getComments(_postId: string): Promise<Array<Comment>>;
    getLikes(postId: string): Promise<Array<Principal>>;
    getMatch(matchId: string): Promise<Match | null>;
    getMatches(): Promise<Array<Match>>;
    getMessages(matchId: string): Promise<Array<ChatMessage>>;
    getMessagesAfter(matchId: string, afterTimestamp: Time): Promise<Array<ChatMessage>>;
    getNotifications(userId: Principal): Promise<Array<Notification>>;
    getPosts(): Promise<Array<PostData>>;
    getPostsCreatedToday(userId: Principal): Promise<bigint>;
    getReports(): Promise<Array<Report>>;
    getStoryViewers(storyId: string): Promise<[bigint, Array<Principal>]>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isBlocked(user1: Principal, user2: Principal): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    likePost(postId: string): Promise<bigint | null>;
    markNotificationsRead(userId: Principal): Promise<void>;
    markReportReviewed(reportId: string): Promise<void>;
    markStoryViewed(storyId: string): Promise<void>;
    reportUser(id: string, reportedUserId: Principal, reportType: string, details: string): Promise<void>;
    requestEmailOTP(email: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "error";
        error: string;
    }>;
    resetDailyLimits(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveChatTheme(matchId: string, theme: string): Promise<void>;
    setCoverPhoto(index: bigint): Promise<void>;
    setVerificationImage(url: string): Promise<void>;
    toggleBlock(targetUserId: Principal): Promise<{
        __kind__: "blockedSuccessfully";
        blockedSuccessfully: boolean;
    } | {
        __kind__: "unblockedSuccessfully";
        unblockedSuccessfully: boolean;
    }>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unlikePost(postId: string): Promise<bigint | null>;
    updatePostsCreatedToday(userId: Principal): Promise<void>;
    updateUserPhotos(photos: Array<UserPhoto>, coverIndex: bigint): Promise<void>;
    verifyEmailOTP(email: string, inputOTP: string): Promise<Variant_ok_expired_invalid_tooManyAttempts>;
}
import type { FeedPost as _FeedPost, Match as _Match, Notification as _Notification, NotificationType as _NotificationType, PostData as _PostData, Story as _Story, StoryType as _StoryType, Time as _Time, UserPhoto as _UserPhoto, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: string, arg1: Comment, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1, arg2);
            return result;
        }
    }
    async addNotification(arg0: Notification, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotification(to_candid_Notification_n8(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotification(to_candid_Notification_n8(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createMatch(arg0: Principal, arg1: Principal, arg2: string): Promise<Match> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(arg0, arg1, arg2);
            return result;
        }
    }
    async createMessage(arg0: ChatMessage, arg1: string): Promise<{
        __kind__: "message";
        message: {
            msgId: string;
            text: string;
            sentAt: Time;
            matchId: string;
            senderUserId: Principal;
        } | null;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createMessage(arg0, arg1);
                return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMessage(arg0, arg1);
            return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNotifications(arg0: Principal, arg1: NotificationType): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotifications(arg0, to_candid_NotificationType_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotifications(arg0, to_candid_NotificationType_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPost(arg0: FeedPost, arg1: string): Promise<FeedPost> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(to_candid_FeedPost_n16(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_FeedPost_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(to_candid_FeedPost_n16(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_FeedPost_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStory(arg0: Story): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStory(to_candid_Story_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStory(to_candid_Story_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteChat(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChat(arg0);
            return result;
        }
    }
    async deleteMatch(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMatch(arg0);
            return result;
        }
    }
    async deleteStory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStory(arg0);
            return result;
        }
    }
    async flagScreenshotAttempt(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.flagScreenshotAttempt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.flagScreenshotAttempt(arg0);
            return result;
        }
    }
    async getActiveStories(): Promise<Array<[Story, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveStories();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveStories();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlockedUsers(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlockedUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlockedUsers(arg0);
            return result;
        }
    }
    async getBlockingUsers(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlockingUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlockingUsers(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatThemes(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatThemes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatThemes();
            return result;
        }
    }
    async getComments(arg0: string): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getLikes(arg0: string): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLikes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLikes(arg0);
            return result;
        }
    }
    async getMatch(arg0: string): Promise<Match | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatches();
            return result;
        }
    }
    async getMessages(arg0: string): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getMessagesAfter(arg0: string, arg1: Time): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesAfter(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesAfter(arg0, arg1);
            return result;
        }
    }
    async getNotifications(arg0: Principal): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPosts(): Promise<Array<PostData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPosts();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPosts();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostsCreatedToday(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsCreatedToday(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsCreatedToday(arg0);
            return result;
        }
    }
    async getReports(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReports();
            return result;
        }
    }
    async getStoryViewers(arg0: string): Promise<[bigint, Array<Principal>]> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoryViewers(arg0);
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoryViewers(arg0);
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async isBlocked(arg0: Principal, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isBlocked(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isBlocked(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async likePost(arg0: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async markNotificationsRead(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationsRead(arg0);
            return result;
        }
    }
    async markReportReviewed(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markReportReviewed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markReportReviewed(arg0);
            return result;
        }
    }
    async markStoryViewed(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markStoryViewed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markStoryViewed(arg0);
            return result;
        }
    }
    async reportUser(arg0: string, arg1: Principal, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportUser(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportUser(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async requestEmailOTP(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "error";
        error: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.requestEmailOTP(arg0);
                return from_candid_variant_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestEmailOTP(arg0);
            return from_candid_variant_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetDailyLimits(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetDailyLimits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetDailyLimits();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveChatTheme(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveChatTheme(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveChatTheme(arg0, arg1);
            return result;
        }
    }
    async setCoverPhoto(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCoverPhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCoverPhoto(arg0);
            return result;
        }
    }
    async setVerificationImage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setVerificationImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setVerificationImage(arg0);
            return result;
        }
    }
    async toggleBlock(arg0: Principal): Promise<{
        __kind__: "blockedSuccessfully";
        blockedSuccessfully: boolean;
    } | {
        __kind__: "unblockedSuccessfully";
        unblockedSuccessfully: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleBlock(arg0);
                return from_candid_variant_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleBlock(arg0);
            return from_candid_variant_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unlikePost(arg0: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePostsCreatedToday(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePostsCreatedToday(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePostsCreatedToday(arg0);
            return result;
        }
    }
    async updateUserPhotos(arg0: Array<UserPhoto>, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserPhotos(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserPhotos(arg0, arg1);
            return result;
        }
    }
    async verifyEmailOTP(arg0: string, arg1: string): Promise<Variant_ok_expired_invalid_tooManyAttempts> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyEmailOTP(arg0, arg1);
                return from_candid_variant_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyEmailOTP(arg0, arg1);
            return from_candid_variant_n49(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_FeedPost_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedPost): FeedPost {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_PostData_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostData): PostData {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_StoryType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoryType): StoryType {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Story_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Story): Story {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        msgId: string;
        text: string;
        sentAt: _Time;
        matchId: string;
        senderUserId: Principal;
    }]): {
    msgId: string;
    text: string;
    sentAt: Time;
    matchId: string;
    senderUserId: Principal;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Match]): Match | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    userName: string;
    userId: Principal;
    createdAt: _Time;
    userPhoto: string;
    userAge: bigint;
    postImage: [] | [string];
    isVerified: boolean;
    caption: [] | [string];
    prompt: [] | [string];
    likesCount: bigint;
    promptAnswer: [] | [string];
}): {
    id: string;
    userName: string;
    userId: Principal;
    createdAt: Time;
    userPhoto: string;
    userAge: bigint;
    postImage?: string;
    isVerified: boolean;
    caption?: string;
    prompt?: string;
    likesCount: bigint;
    promptAnswer?: string;
} {
    return {
        id: value.id,
        userName: value.userName,
        userId: value.userId,
        createdAt: value.createdAt,
        userPhoto: value.userPhoto,
        userAge: value.userAge,
        postImage: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.postImage)),
        isVerified: value.isVerified,
        caption: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.caption)),
        prompt: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.prompt)),
        likesCount: value.likesCount,
        promptAnswer: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.promptAnswer))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    storyType: _StoryType;
    userId: Principal;
    createdAt: _Time;
    overlayText: [] | [string];
    mediaUrl: string;
    viewers: Array<Principal>;
    youtubeVidId: [] | [string];
    youtubeTtitle: [] | [string];
    location: [] | [string];
}): {
    id: string;
    storyType: StoryType;
    userId: Principal;
    createdAt: Time;
    overlayText?: string;
    mediaUrl: string;
    viewers: Array<Principal>;
    youtubeVidId?: string;
    youtubeTtitle?: string;
    location?: string;
} {
    return {
        id: value.id,
        storyType: from_candid_StoryType_n29(_uploadFile, _downloadFile, value.storyType),
        userId: value.userId,
        createdAt: value.createdAt,
        overlayText: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.overlayText)),
        mediaUrl: value.mediaUrl,
        viewers: value.viewers,
        youtubeVidId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.youtubeVidId)),
        youtubeTtitle: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.youtubeTtitle)),
        location: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    avatarData: [] | [string];
    name: string;
    isDemo: boolean;
    isVerified: boolean;
    gender: string;
    coverPhotoIndex: bigint;
    photo: string;
    planType: string;
    photos: Array<_UserPhoto>;
    verificationImage: [] | [string];
}): {
    age: bigint;
    avatarData?: string;
    name: string;
    isDemo: boolean;
    isVerified: boolean;
    gender: string;
    coverPhotoIndex: bigint;
    photo: string;
    planType: string;
    photos: Array<UserPhoto>;
    verificationImage?: string;
} {
    return {
        age: value.age,
        avatarData: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.avatarData)),
        name: value.name,
        isDemo: value.isDemo,
        isVerified: value.isVerified,
        gender: value.gender,
        coverPhotoIndex: value.coverPhotoIndex,
        photo: value.photo,
        planType: value.planType,
        photos: value.photos,
        verificationImage: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.verificationImage))
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    notificationType: _NotificationType;
    read: boolean;
    text: string;
    toUserId: Principal;
    fromPhoto: string;
    timestamp: _Time;
    fromName: string;
}): {
    id: string;
    notificationType: NotificationType;
    read: boolean;
    text: string;
    toUserId: Principal;
    fromPhoto: string;
    timestamp: Time;
    fromName: string;
} {
    return {
        id: value.id,
        notificationType: from_candid_NotificationType_n40(_uploadFile, _downloadFile, value.notificationType),
        read: value.read,
        text: value.text,
        toUserId: value.toUserId,
        fromPhoto: value.fromPhoto,
        timestamp: value.timestamp,
        fromName: value.fromName
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    key: string;
    didLike: boolean;
    post: _FeedPost;
    likesCount: bigint;
}): {
    key: string;
    didLike: boolean;
    post: FeedPost;
    likesCount: bigint;
} {
    return {
        key: value.key,
        didLike: value.didLike,
        post: from_candid_FeedPost_n18(_uploadFile, _downloadFile, value.post),
        likesCount: value.likesCount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Story, bigint]): [Story, bigint] {
    return [
        from_candid_Story_n27(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    message: [] | [{
            msgId: string;
            text: string;
            sentAt: _Time;
            matchId: string;
            senderUserId: Principal;
        }];
}): {
    __kind__: "message";
    message: {
        msgId: string;
        text: string;
        sentAt: Time;
        matchId: string;
        senderUserId: Principal;
    } | null;
} {
    return "message" in value ? {
        __kind__: "message",
        message: from_candid_opt_n15(_uploadFile, _downloadFile, value.message)
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    image: null;
}): StoryType {
    return "video" in value ? StoryType.video : "image" in value ? StoryType.image : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    likePost: null;
} | {
    likePhoto: null;
} | {
    commentPost: null;
} | {
    likePrompt: null;
}): NotificationType {
    return "likePost" in value ? NotificationType.likePost : "likePhoto" in value ? NotificationType.likePhoto : "commentPost" in value ? NotificationType.commentPost : "likePrompt" in value ? NotificationType.likePrompt : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    error: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "error";
    error: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "error" in value ? {
        __kind__: "error",
        error: value.error
    } : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blockedSuccessfully: boolean;
} | {
    unblockedSuccessfully: boolean;
}): {
    __kind__: "blockedSuccessfully";
    blockedSuccessfully: boolean;
} | {
    __kind__: "unblockedSuccessfully";
    unblockedSuccessfully: boolean;
} {
    return "blockedSuccessfully" in value ? {
        __kind__: "blockedSuccessfully",
        blockedSuccessfully: value.blockedSuccessfully
    } : "unblockedSuccessfully" in value ? {
        __kind__: "unblockedSuccessfully",
        unblockedSuccessfully: value.unblockedSuccessfully
    } : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    expired: null;
} | {
    invalid: null;
} | {
    tooManyAttempts: null;
}): Variant_ok_expired_invalid_tooManyAttempts {
    return "ok" in value ? Variant_ok_expired_invalid_tooManyAttempts.ok : "expired" in value ? Variant_ok_expired_invalid_tooManyAttempts.expired : "invalid" in value ? Variant_ok_expired_invalid_tooManyAttempts.invalid : "tooManyAttempts" in value ? Variant_ok_expired_invalid_tooManyAttempts.tooManyAttempts : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Story, bigint]>): Array<[Story, bigint]> {
    return value.map((x)=>from_candid_tuple_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PostData>): Array<PostData> {
    return value.map((x)=>from_candid_PostData_n43(_uploadFile, _downloadFile, x));
}
function to_candid_FeedPost_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeedPost): _FeedPost {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_NotificationType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): _NotificationType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Notification_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Notification): _Notification {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_StoryType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StoryType): _StoryType {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Story_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Story): _Story {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    userName: string;
    userId: Principal;
    createdAt: Time;
    userPhoto: string;
    userAge: bigint;
    postImage?: string;
    isVerified: boolean;
    caption?: string;
    prompt?: string;
    likesCount: bigint;
    promptAnswer?: string;
}): {
    id: string;
    userName: string;
    userId: Principal;
    createdAt: _Time;
    userPhoto: string;
    userAge: bigint;
    postImage: [] | [string];
    isVerified: boolean;
    caption: [] | [string];
    prompt: [] | [string];
    likesCount: bigint;
    promptAnswer: [] | [string];
} {
    return {
        id: value.id,
        userName: value.userName,
        userId: value.userId,
        createdAt: value.createdAt,
        userPhoto: value.userPhoto,
        userAge: value.userAge,
        postImage: value.postImage ? candid_some(value.postImage) : candid_none(),
        isVerified: value.isVerified,
        caption: value.caption ? candid_some(value.caption) : candid_none(),
        prompt: value.prompt ? candid_some(value.prompt) : candid_none(),
        likesCount: value.likesCount,
        promptAnswer: value.promptAnswer ? candid_some(value.promptAnswer) : candid_none()
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    storyType: StoryType;
    userId: Principal;
    createdAt: Time;
    overlayText?: string;
    mediaUrl: string;
    viewers: Array<Principal>;
    youtubeVidId?: string;
    youtubeTtitle?: string;
    location?: string;
}): {
    id: string;
    storyType: _StoryType;
    userId: Principal;
    createdAt: _Time;
    overlayText: [] | [string];
    mediaUrl: string;
    viewers: Array<Principal>;
    youtubeVidId: [] | [string];
    youtubeTtitle: [] | [string];
    location: [] | [string];
} {
    return {
        id: value.id,
        storyType: to_candid_StoryType_n23(_uploadFile, _downloadFile, value.storyType),
        userId: value.userId,
        createdAt: value.createdAt,
        overlayText: value.overlayText ? candid_some(value.overlayText) : candid_none(),
        mediaUrl: value.mediaUrl,
        viewers: value.viewers,
        youtubeVidId: value.youtubeVidId ? candid_some(value.youtubeVidId) : candid_none(),
        youtubeTtitle: value.youtubeTtitle ? candid_some(value.youtubeTtitle) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    avatarData?: string;
    name: string;
    isDemo: boolean;
    isVerified: boolean;
    gender: string;
    coverPhotoIndex: bigint;
    photo: string;
    planType: string;
    photos: Array<UserPhoto>;
    verificationImage?: string;
}): {
    age: bigint;
    avatarData: [] | [string];
    name: string;
    isDemo: boolean;
    isVerified: boolean;
    gender: string;
    coverPhotoIndex: bigint;
    photo: string;
    planType: string;
    photos: Array<_UserPhoto>;
    verificationImage: [] | [string];
} {
    return {
        age: value.age,
        avatarData: value.avatarData ? candid_some(value.avatarData) : candid_none(),
        name: value.name,
        isDemo: value.isDemo,
        isVerified: value.isVerified,
        gender: value.gender,
        coverPhotoIndex: value.coverPhotoIndex,
        photo: value.photo,
        planType: value.planType,
        photos: value.photos,
        verificationImage: value.verificationImage ? candid_some(value.verificationImage) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    notificationType: NotificationType;
    read: boolean;
    text: string;
    toUserId: Principal;
    fromPhoto: string;
    timestamp: Time;
    fromName: string;
}): {
    id: string;
    notificationType: _NotificationType;
    read: boolean;
    text: string;
    toUserId: Principal;
    fromPhoto: string;
    timestamp: _Time;
    fromName: string;
} {
    return {
        id: value.id,
        notificationType: to_candid_NotificationType_n10(_uploadFile, _downloadFile, value.notificationType),
        read: value.read,
        text: value.text,
        toUserId: value.toUserId,
        fromPhoto: value.fromPhoto,
        timestamp: value.timestamp,
        fromName: value.fromName
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): {
    likePost: null;
} | {
    likePhoto: null;
} | {
    commentPost: null;
} | {
    likePrompt: null;
} {
    return value == NotificationType.likePost ? {
        likePost: null
    } : value == NotificationType.likePhoto ? {
        likePhoto: null
    } : value == NotificationType.commentPost ? {
        commentPost: null
    } : value == NotificationType.likePrompt ? {
        likePrompt: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StoryType): {
    video: null;
} | {
    image: null;
} {
    return value == StoryType.video ? {
        video: null
    } : value == StoryType.image ? {
        image: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
